### ISSUE TITLE
Arquivo readme que achei interessante.

### ISSUE THREAD

**Issue by AdrBender** [adrianoleitedasilva/best-markdown-files#1]
https://github.com/onimur/onimur

**Comment by adrianoleitedasilva** [comment]
Meu caro, bom dia. 

Primeiramente, feliz ano novo. Muita paz e sucesso para você.

Gostaria de agradecer o envio deste readme, simplesmente ele está fantástico. Já até peguei algumas coisas para remontar o meu.  rsrsrsrsrs.

Forte abraço.

**Comment by AdrBender** [comment]
Tem um monte interessante aqui ó >> https://github.com/abhisheknaiidu/awesome-github-profile-readme

**Comment by adrianoleitedasilva** [comment]
Opa, boa noite.

Olhei e achei bem interessante. Obrigado por compartilhar comigo.
